Add Comment to Idea
tunagch190847/COMP1640-Web-Project pull request #75
Opened 2023-03-10 14:37 UTC by tunagch190847

2023-03-10 19:23 UTC, TripleVi requested changes

2023-03-10 19:23 UTC, TripleVi commented on be/src/modules/idea/idea.service.ts
> +    }
- Cái validate comment này sao không check ở DTO luôn
- Chưa có check user permission

2023-03-10 19:23 UTC, TripleVi commented on be/src/modules/idea/idea.service.ts
> +  }
- Sao không dùng hàm `getOneIdea` luôn mà phải tạo hàm này

2023-03-10 19:23 UTC, TripleVi commented on be/src/modules/idea/idea.service.ts
> +    });
- Có mỗi một record thì sao phải cho vào transaction
- Chưa xử lý các thông tin khác liên quan đến `level`, `parent_id`

2023-03-11 10:30 UTC, tunagch190847 commented on be/src/modules/idea/idea.service.ts
> +    }
dto chỉ throw ra lỗi mặc định, ở đây mình muốn throw ra lỗi của mình thì thêm thôi

2023-03-11 10:30 UTC, tunagch190847 commented on be/src/modules/idea/idea.service.ts
> +  }
ok không thấy

2023-03-11 10:31 UTC, tunagch190847 commented on be/src/modules/idea/idea.service.ts
> +    });
chưa hiểu về level với parent_id ông mong muốn . Bởi vì cái level với parent_id ông tự thêm, cũng ko trao đổi với tôi nên tôi chưa biết là gì nên tôi ko thêm

2023-03-12 08:18 UTC, TripleVi commented on be/src/modules/idea/idea.service.ts
> +    });
- cái comment thì lúc thảo luận ý tưởng mọi người có thống nhất là làm cái comment như kiểu fb ấy
- nếu mà không cho reply thì tất cả comment là ngang hàng đúng không, còn nếu cho reply comment của thằng khác thì sẽ sinh ra level
- cái parent_id là mình lưu comment_id của cái comment mà mình reply để mình có thể biết cái comment này là con của thằng nào cũng như sử dụng cho lúc hiển thị ấy
- mình set max level là 3 (ô xem thử cái comment trên fb xem, có gì chưa hợp lý thì thảo luận)

2023-03-12 08:21 UTC, TripleVi commented on be/src/modules/idea/idea.service.ts
> +    });
ừ còn hôm trước tôi sửa entity, tôi chưa thảo luận với ô về cái parent_id với level, lỗi tôi :))

2023-03-17 11:15 UTC, merged